spring:
  datasource:
    hikari:
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 30000
      username: root
      password: "0216"
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 50
      jdbc-url: jdbc:mysql://127.0.0.1:3306/DEMO
    url: jdbc:mysql://127.0.0.1:3306/DEMO
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.order_inserts: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
